### ISSUE TITLE
[기타] : ranking 브랜치명 수정 요망

### ISSUE THREAD

**Issue by Garden-L** [JeongWonLim/OSS-Team5#12]
**설명**
- 랭킹 브랜치명이 정확히 어떤 브랜치인지 확실하게 수정부탁해.

브랜치명 양식
1. 클린 코드 수정 브랜치명 : Modify_Code
2. 기능 추가 브랜치 명 : Add_(추가기능)
3. 디폴트 브랜치 : dev 
- 디폴트 브랜치는 지속적인 개발 가능한 상태로 유지된 브랜치다. (Clone될 브랜치).
4. 마스터 브랜치 : master
- 마스터 브랜치는 실질적으로 출시할 상태의 파일이 있는 브랜치다.

**Comment by hkmast** [comment]
merge 시키기 전에 한번에 수정해서 다시 올려볼게
