### ISSUE TITLE
[버그] runGameVSCom 비정상 실행

### ISSUE THREAD

**Issue by GitKosy** [JeongWonLim/OSS-Team5#14]
**설명**
사용자지정값을 받을경우 컴퓨터 차례가 정상적으로 실행되지 않는 오류 발생

**버그 발생 과정**
동작 재현:
1. 게임모드 선택 중 컴퓨터 대 사용자 모드 선택
2. 난이도 임의 선택
3. 사용자 말 선택 ( O, X )
4. 사용자 좌표 입력

**스크린샷**
![버그1](https://user-images.githubusercontent.com/55682017/69400783-4bd70800-0d36-11ea-8aed-937c8f69edb5.PNG)
![버그2](https://user-images.githubusercontent.com/55682017/69400792-52657f80-0d36-11ea-9276-5424952ab67a.PNG)

**실행환경:**
 - OS :  Windows 10 
 - IDE :  Visual Studio 2015

**연관된 글**
해결 : 
참고 : 
미해결 :

**Comment by Garden-L** [comment]
지금 이거 어느 코드 부분에서 문제생기는거야? 알고리즘 부분이야?

**Comment by GitKosy** [comment]
ComputerTurn에서 minMax를 호출하는 과정에서 문제가 발생한거같아.

**Comment by GitKosy** [comment]
ComputerTurn에서
