### ISSUE TITLE
[기타] : #15 재 클론시키고 풀리퀘스트 요망

### ISSUE THREAD

**Issue by Garden-L** [JeongWonLim/OSS-Team5#16]
**설명**
#15 풀리퀘스트 된 것보니 깐 @hkmast 민성이가 prinBoard 수정했었는데 지금 수정된 파일이 아니라 이전 파일같아 클론시켜서 다시 작성해야될 것같아.

**스크린샷**
![image](https://user-images.githubusercontent.com/56042451/69435417-dfcec100-0d82-11ea-80a2-a61c4644aed9.png)

![image](https://user-images.githubusercontent.com/56042451/69435471-f4ab5480-0d82-11ea-8366-b81616690c19.png)

**연관된 글**
참고 : #15

**Comment by shwon79** [comment]
확인했고 페치해서 수정하고 다시 올릴게
