### ISSUE TITLE
[형식] : 코드 수정 요망

### ISSUE THREAD

**Issue by Garden-L** [JeongWonLim/OSS-Team5#17]
***설명***
- 숫자 잘못 적혀있음. 난이도 2와 3이 같은 번호로 되어있어서 수정 해야될 것같아.

![image](https://user-images.githubusercontent.com/56042451/69436518-dcd4d000-0d84-11ea-8577-f0cb60d22e8c.png)

**Comment by GitKosy** [comment]
확인하였구 수정할게
