### ISSUE TITLE
[버그]:위치 입력 오류

### ISSUE THREAD

**Issue by Garden-L** [JeongWonLim/OSS-Team5#18]
**설명**
- 보드 위치 값이랑 출력 값이랑 다르다. 스크린샷을 보면 알겠지만 1,1 입력했는데 2,2에 표시된다.

**버그 발생 과정**
동작 재현:
1. 나타난 번호대로 입력한다

**스크린샷**
![image](https://user-images.githubusercontent.com/56042451/69437282-5620f280-0d86-11ea-9dee-8d2ab83be1e9.png)

**실행환경:**
 - OS :  윈도우 10
 - IDE :  Visual Studio 2015

**Comment by hkmast** [comment]
이거 랭킹 올리면서 조정해볼게
