### ISSUE TITLE
[버그] : 함수 호출 오류

### ISSUE THREAD

**Issue by Garden-L** [JeongWonLim/OSS-Team5#25]
**설명**
- 없는 함수로 떠서 실행이 안됩니다. 

**스크린샷**
![image](https://user-images.githubusercontent.com/56042451/69497303-c2365e80-0f1e-11ea-8eb6-383c09fd2598.png)

**실행환경:**
 - OS :  Windows 10 
 - IDE :  Visual Studio 2015

**Comment by hkmast** [comment]
기존에 있던 fp 포인터를  가독성 있게 바꾸려고 rankingFile 로 이름을 바꾸다가 fprintf_s함수에 앞부분 fp까지 바뀌어서 이상한 함수명이 된것같아 변경전에 다시 체크해야 됐었는데 미안

**Comment by Garden-L** [comment]
이부분은 수정 완료
