### ISSUE TITLE
[형식] : 기능별로 파일 분할

### ISSUE THREAD

**Issue by Garden-L** [JeongWonLim/OSS-Team5#27]
### 설명
- 지금 한 파일내에 너무 많은 함수들이 담겨있어서 기능별로 파일 분할 시키는 것은 어때?

**Comment by GitKosy** [comment]
만약 진행한다면, 의견으로는
**GameProgress.c**  isAWin , is3inARow , isBoardFull
**UI.c**  showMenu , computerLvlSelect , printBoard
**Rank.c** printRanking, insertRanking
나머지는 TTTFunc에 남기기

**Comment by hkmast** [comment]
선엽이 의견 괜찮은것 동의해

**Comment by hkmast** [comment]
선엽이 의견 괜찮은것 같아 동의해

**Comment by shwon79** [comment]
선엽이 의견 괜찮다 너무 많은 파일로 분할하는 것 같지도 않고 기능별로 잘 묶은것 같아

**Comment by Garden-L** [comment]
이 이슈는 진행하지 않는걸로 할께
크게 차이가 없을것같아
