### ISSUE TITLE
[문서] : README 사진 출력오류

### ISSUE THREAD

**Issue by GitKosy** [JeongWonLim/OSS-Team5#28]
사진출력이 제대로 안되고 있는 문제가 발생중
![github readme오류](https://user-images.githubusercontent.com/55682017/69543407-e3f01e00-0fd0-11ea-938c-f5c889b9d5a2.PNG)

**Comment by hkmast** [comment]
그러게 이부분 직접 url 쳐봐도 안나오네

**Comment by hkmast** [comment]
<img src="https://github.com/JeongWonLim/OSS-Team5/blob/dev/image/%EC%82%AC%EC%9A%A9%EB%B0%A9%EB%B2%951.png?raw=true" width="399px" height="234px" />
