### ISSUE TITLE
[버그] rank파일에 기록이 남지 않는 문제

### ISSUE THREAD

**Issue by GitKosy** [JeongWonLim/OSS-Team5#31]
**설명**
틱택토 사용자 대 컴퓨터 모드 에서 기록이 저장되지 않는 문제발생

**버그 발생 과정**
동작 재현: 프로젝트에서 생성된 틱택토 exe파일을 실행시킨다.
1. 컴퓨터와의 대전을 진행하여 승리한다.
2. 기록을 저장한다.
3. rank.txt파일을 실행한다.

**스크린샷**
![틱택토 랭크저장](https://user-images.githubusercontent.com/55682017/69604038-a71f3800-105f-11ea-8011-24027607c144.PNG)
![빈문서](https://user-images.githubusercontent.com/55682017/69604041-a71f3800-105f-11ea-82eb-c092a6ad2598.PNG)

**실행환경:**
 - OS :   Windows 10 
 - IDE :  Visual Studio 2015

**Comment by hkmast** [comment]
![image](https://user-images.githubusercontent.com/50509845/69643060-16b81600-10a6-11ea-9e63-12bd460a91a1.png)
음... 자세한 환경을 적어줘 일단은 내가 다시 실행해 봤을 때는 exe파일의 위치에 맞게 랭크파일이 정상적으로 생성됨

**Comment by Garden-L** [comment]
이거 내가 주석처리 해놨는데 그부분이 안돌아가서 그런걸꺼야 수정해서 올릴께

**Comment by hkmast** [comment]
수정됨
