### ISSUE TITLE
[버그]분할컴파일 VS 오류번호2005

### ISSUE THREAD

**Issue by hkmast** [JeongWonLim/OSS-Team5#5]
**설명**
1. 분할 컴파일 한 부분 funcTTT.c 과 Min_Max_Alg.c 부분에서 같은 함수가 중첩됨
2. 프로젝트 내에 여러번 정의가 된 기호가 있다고 나옴

**버그 발생 과정**
1. 오류로 인한 디버깅 실패

**스크린샷**
![image](https://user-images.githubusercontent.com/50509845/68857057-533e5600-0725-11ea-9ebb-4cf78b1bef53.png)

**실행환경:**
 - OS :  Windows 10 
 - IDE :  Visual Studio 2015

**Comment by shwon79** [comment]
TTTFunc에서 min, max, minMax함수를 지우면 될 것 같아

**Comment by GitKosy** [comment]
오케이

**Comment by hkmast** [comment]
수정완료
