### ISSUE TITLE
[버그] visualization 브랜치에서의 변수명 오류

### ISSUE THREAD

**Issue by shwon79** [JeongWonLim/OSS-Team5#6]
**설명**
visualization브랜치에서의 TTTFunc.c 파일의 printBoard함수에서 A_SIZE를 A_size로 사용하여 컴파일 오류가 발생함.

**버그 발생 과정**
1. basedef.h에서 정의된 A_SIZE를 A_size 잘못 적어 오류가 난 것.

**스크린샷**
![에러](https://user-images.githubusercontent.com/55779075/68859436-96e78e80-072a-11ea-941e-2bacdb3b6606.PNG)

**실행환경:**
 - OS :  Windows 10 
 - IDE :  Visual Studio 2015

**Comment by hkmast** [comment]
확인했어 수정한 부분 올릴게
