### ISSUE TITLE
[버그] HumanTurn함수에서 런타임 에러 발생

### ISSUE THREAD

**Issue by shwon79** [JeongWonLim/OSS-Team5#7]
**설명**
HumanTurn함수에서 행번호와 열번호를 입력받을 때 유효하지 않은 값 (예: 문자, 너무 크거나 작은 값)을 입력할 시에 작동이 중지됨.

**버그 발생 과정**
1. 사람이 심볼을 어느 위치에 둘 지 선택하는 과정(HumanTurn함수)에서 유효하지 않은 값 입력시 런타임 에러 발생

**스크린샷**
![에러2](https://user-images.githubusercontent.com/55779075/68863955-a8816400-0733-11ea-9bd8-00bb23a2d661.PNG)
![에러5](https://user-images.githubusercontent.com/55779075/68863958-ac14eb00-0733-11ea-97a2-0f606aed57ea.PNG)

**실행환경:**
 - OS :  Windows 10 
 - IDE :  Visual Studio 2015

**Comment by Garden-L** [comment]
이 부분은 내가 수정해도 될까?

**Comment by hkmast** [comment]
문자입력은 안해봐서 몰랐는데
@JeongWonLim  혹시 입력할때 1~3 입력받는걸로 해줄수 있어?

**Comment by Garden-L** [comment]
그럼 그 부분은 내가 수정하도록 할께
